
---

### `about.qmd`
```markdown
---
title: "About"
---

# About Me

I’m a junior Data Analytics major at Denison University, and I also study Applied Mathematics and Vocal Performance. I enjoy turning messy data into clear insights and communicating results in a reproducible way.

## Skills
- **Programming:** R (tidyverse), (Python), SQL  
- **Tools:** Git/GitHub, Quarto, Excel, Power BI  
- **Analytics:** visualization, modeling, experimental design, reporting

## What I’m working on
- I am learning in-depth descriptive data analytics methods, including Natural Language Processing and Computer Vision. 
- I am looking forward to returning to Union Home Mortgage this summer as a Strategic Data Analytics Intern, where I will be using R Studio and Power BI to analyze information and make useful and justified suggestion for improvement areas throughout the company. 

## Coursework
- Data Systems 
- Linear Algebra and Differential Equations 
- Statistical Theory
- Probabilistic Modeling 
- Design and Data Analysis for Social Impact
- Advanced Descriptive Methods in Data Analytics

## Resume
Linkedin: www.linkedin.com/in/maddie-geschke 
